-- Clerk organization memberships
-- Access clerk_user_id through user_id -> auth_clerk_users.clerk_user_id relationship

create table if not exists "public"."auth_clerk_orgs_members" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now() not null,
    "auth_clerk_users_id" bigint,
    "clerk_org_id" bigint not null,
    "clerk_org_role" public.clerk_org_role default 'member'::public.clerk_org_role not null
);

comment on table "public"."auth_clerk_orgs_members" is 'Clerk organization memberships. Access clerk_user_id through user_id -> auth_clerk_users.clerk_user_id relationship';
comment on column "public"."auth_clerk_orgs_members"."auth_clerk_users_id" is 'foreign key to auth_clerk_users.id';
comment on column "public"."auth_clerk_orgs_members"."clerk_org_role" is 'Organization-specific role: admin (manage org), member (standard access), viewer (read-only access). Business roles are in auth_clerk_users.role column.';

alter table "public"."auth_clerk_orgs_members" enable row level security;

alter table "public"."auth_clerk_orgs_members" add constraint "auth_clerk_orgs_members_pkey" primary key ("id");
alter table "public"."auth_clerk_orgs_members" add constraint "auth_clerk_orgs_members_auth_clerk_users_id_fkey" foreign key ("auth_clerk_users_id") references "public"."auth_clerk_users" ("id");
alter table "public"."auth_clerk_orgs_members" add constraint "auth_clerk_orgs_members_clerk_org_id_fkey" foreign key ("clerk_org_id") references "public"."auth_clerk_orgs" ("id");
