-- Table: public.contact_contact_types
-- Junction table linking contacts to their contact types (many-to-many)
CREATE TABLE public.contact_contact_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id bigint NOT NULL REFERENCES contact(id) ON DELETE CASCADE,
  contact_types_id bigint NOT NULL REFERENCES contact_types(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(contact_id, contact_types_id)
);

COMMENT ON TABLE contact_contact_types IS 'Junction table linking contacts to their contact types (many-to-many)';

ALTER TABLE public.contact_contact_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "contact_contact_types_select_authenticated" ON contact_contact_types 
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "contact_contact_types_insert_authenticated" ON contact_contact_types 
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "contact_contact_types_update_authenticated" ON contact_contact_types 
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "contact_contact_types_delete_authenticated" ON contact_contact_types 
  FOR DELETE TO authenticated USING (true);

