-- Table: public.contact_types
-- Lookup table defining types of contacts (what a contact IS)
CREATE TABLE public.contact_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,      -- 'borrower_assistant' (stable, for code)
  name text NULL,                 -- 'Borrower Assistant' (for display)
  description text,
  allows_multiple boolean DEFAULT true,  -- Can a contact have multiple instances of this type?
  display_order int,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone NULL DEFAULT (now() AT TIME ZONE 'utc'::text),
  updated_at timestamp with time zone NULL DEFAULT (now() AT TIME ZONE 'utc'::text)
);

COMMENT ON TABLE contact_types IS 'Lookup table defining types of contacts (what a contact IS professionally)';
COMMENT ON COLUMN contact_types.code IS 'Snake_case identifier for programmatic use (stable, use in code/APIs)';
COMMENT ON COLUMN contact_types.name IS 'Human-readable display name';
COMMENT ON COLUMN contact_types.description IS 'Description of this contact type';
COMMENT ON COLUMN contact_types.allows_multiple IS 'Whether a contact can have multiple instances of this type';
COMMENT ON COLUMN contact_types.display_order IS 'Sort order for UI display';

ALTER TABLE public.contact_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "contact_types_select_authenticated" ON contact_types 
  FOR SELECT TO authenticated USING (true);
