-- Table: public.deal_roles
-- Junction table linking deals to parties (contacts or users) with their role on that specific deal
CREATE TABLE public.deal_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NOT NULL REFERENCES deal(id) ON DELETE CASCADE,
  deal_role_types_id bigint REFERENCES deal_role_types(id),
  
  -- Party can be contact OR user (mutually exclusive)
  contact_id bigint REFERENCES contact(id) ON DELETE CASCADE,
  auth_clerk_users_id bigint REFERENCES auth_clerk_users(id) ON DELETE CASCADE,
  
  notes text,
  created_at timestamptz DEFAULT now(),
  
  -- Party must be either contact OR user
  CONSTRAINT deal_roles_has_party CHECK (
    (contact_id IS NOT NULL AND auth_clerk_users_id IS NULL) OR
    (contact_id IS NULL AND auth_clerk_users_id IS NOT NULL) OR
    (contact_id IS NULL AND auth_clerk_users_id IS NULL) -- Allow during migration
  )
);

COMMENT ON TABLE deal_roles IS 'Junction table linking deals to parties (contacts or users) with their role on that specific deal';
COMMENT ON COLUMN deal_roles.deal_id IS 'The deal this party is associated with';
COMMENT ON COLUMN deal_roles.deal_role_types_id IS 'The role this party plays on the deal';
COMMENT ON COLUMN deal_roles.contact_id IS 'Reference to contact table (for external parties)';
COMMENT ON COLUMN deal_roles.auth_clerk_users_id IS 'Reference to auth_clerk_users table (for internal users/logged-in parties)';
COMMENT ON COLUMN deal_roles.notes IS 'Optional notes about this party assignment';

-- Unique constraints to prevent duplicate role assignments
CREATE UNIQUE INDEX deal_roles_unique_contact_role 
  ON deal_roles (deal_id, deal_role_types_id, contact_id) 
  WHERE contact_id IS NOT NULL;

CREATE UNIQUE INDEX deal_roles_unique_user_role 
  ON deal_roles (deal_id, deal_role_types_id, auth_clerk_users_id) 
  WHERE auth_clerk_users_id IS NOT NULL;

-- Indexes for common queries
CREATE INDEX deal_roles_deal_id_idx ON deal_roles(deal_id);
CREATE INDEX deal_roles_contact_id_idx ON deal_roles(contact_id) WHERE contact_id IS NOT NULL;
CREATE INDEX deal_roles_user_id_idx ON deal_roles(auth_clerk_users_id) WHERE auth_clerk_users_id IS NOT NULL;
CREATE INDEX deal_roles_role_types_id_idx ON deal_roles(deal_role_types_id);

ALTER TABLE public.deal_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deal_roles_select_authenticated" ON deal_roles 
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "deal_roles_insert_authenticated" ON deal_roles 
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "deal_roles_update_authenticated" ON deal_roles 
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "deal_roles_delete_authenticated" ON deal_roles 
  FOR DELETE TO authenticated USING (true);
