-- Table: public.deal_role_types
-- Lookup table defining roles that parties can play on a specific deal
CREATE TABLE public.deal_role_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,      -- snake_case (stable, for code)
  name text NOT NULL,             -- Title Case (for display)
  description text,
  allows_multiple boolean DEFAULT true,  -- Can a deal have 2+ parties in this role?
  display_order int,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE deal_role_types IS 'Lookup table defining roles that parties can play on a specific deal (e.g., Broker, Title Agent, Guarantor)';
COMMENT ON COLUMN deal_role_types.code IS 'Snake_case identifier for programmatic use (stable, use in code/APIs)';
COMMENT ON COLUMN deal_role_types.name IS 'Human-readable display name';
COMMENT ON COLUMN deal_role_types.allows_multiple IS 'Whether a deal can have multiple parties in this role';
COMMENT ON COLUMN deal_role_types.display_order IS 'Sort order for UI display';

ALTER TABLE public.deal_role_types ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deal_role_types_select_authenticated" ON deal_role_types 
  FOR SELECT TO authenticated USING (true);
