-- Table: public.deal_guarantors
-- Junction table linking deals to guarantors (many-to-many)
CREATE TABLE public.deal_guarantors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NOT NULL REFERENCES deal(id) ON DELETE CASCADE,
  guarantor_id bigint NOT NULL REFERENCES guarantor(id) ON DELETE CASCADE,
  is_primary boolean DEFAULT false,
  display_order int,
  notes text,
  created_at timestamptz DEFAULT now(),
  
  -- Prevent duplicate guarantor assignments to same deal
  CONSTRAINT deal_guarantors_unique UNIQUE (deal_id, guarantor_id)
);

COMMENT ON TABLE deal_guarantors IS 'Junction table linking deals to guarantors (many-to-many)';
COMMENT ON COLUMN deal_guarantors.deal_id IS 'The deal this guarantor is associated with';
COMMENT ON COLUMN deal_guarantors.guarantor_id IS 'Reference to guarantor table';
COMMENT ON COLUMN deal_guarantors.is_primary IS 'Whether this is the primary guarantor for the deal';
COMMENT ON COLUMN deal_guarantors.display_order IS 'Order of guarantors (1 = primary, 2 = secondary, etc.)';
COMMENT ON COLUMN deal_guarantors.notes IS 'Optional notes about this guarantor assignment';

-- Indexes
CREATE INDEX deal_guarantors_deal_id_idx ON deal_guarantors(deal_id);
CREATE INDEX deal_guarantors_guarantor_id_idx ON deal_guarantors(guarantor_id);

-- RLS
ALTER TABLE public.deal_guarantors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deal_guarantors_select_authenticated" ON deal_guarantors 
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "deal_guarantors_insert_authenticated" ON deal_guarantors 
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "deal_guarantors_update_authenticated" ON deal_guarantors 
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "deal_guarantors_delete_authenticated" ON deal_guarantors 
  FOR DELETE TO authenticated USING (true);
