/**
 * Re-export all types from database.types.ts
 *
 * This file is deprecated in favor of @/types/database.types.ts
 * which is auto-generated by the Supabase CLI.
 *
 * @deprecated Use import { ... } from "@/types/database.types" instead
 */
export * from "./database.types";
