-- Migration: Create junction table for transfer-to-vendor matching
-- Stage 1: Basic version for manual matching (one transfer to one vendor)

CREATE TABLE IF NOT EXISTS "public"."api_brex_transfers_vendors" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "brex_transfer_id" text NOT NULL,
    "brex_vendor_id" bigint NOT NULL,
    "match_method" text DEFAULT 'manual',
    "match_notes" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "api_brex_transfers_vendors_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "api_brex_transfers_vendors_brex_transfer_id_key" UNIQUE ("brex_transfer_id"),
    CONSTRAINT "api_brex_transfers_vendors_brex_transfer_id_fkey" FOREIGN KEY ("brex_transfer_id") REFERENCES "public"."api_brex_transfers"("brex_transfer_id") ON DELETE CASCADE,
    CONSTRAINT "api_brex_transfers_vendors_brex_vendor_id_fkey" FOREIGN KEY ("brex_vendor_id") REFERENCES "public"."api_brex_vendors"("id") ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "api_brex_transfers_vendors_brex_transfer_id_idx" ON "public"."api_brex_transfers_vendors"("brex_transfer_id");
CREATE INDEX IF NOT EXISTS "api_brex_transfers_vendors_brex_vendor_id_idx" ON "public"."api_brex_transfers_vendors"("brex_vendor_id");

-- Enable RLS
ALTER TABLE "public"."api_brex_transfers_vendors" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Allow service_role full access
CREATE POLICY "Service role can manage transfer-vendor matches" ON "public"."api_brex_transfers_vendors"
    FOR ALL USING (auth.role() = 'service_role');

-- Allow admins full access (check if user has admin role)
CREATE POLICY "Admins can manage transfer-vendor matches" ON "public"."api_brex_transfers_vendors"
    FOR ALL TO authenticated
    USING (
        EXISTS (
            SELECT 1 FROM "public"."auth_clerk_users" acu
            WHERE acu.clerk_user_id = auth.jwt()->>'sub'
            AND acu.role = 'admin'::user_role_internal
        )
    )
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM "public"."auth_clerk_users" acu
            WHERE acu.clerk_user_id = auth.jwt()->>'sub'
            AND acu.role = 'admin'::user_role_internal
        )
    );

-- Grant execute permission
GRANT ALL ON TABLE "public"."api_brex_transfers_vendors" TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."api_brex_transfers_vendors" TO authenticated;

-- Comment
COMMENT ON TABLE "public"."api_brex_transfers_vendors" IS 
'Junction table linking Brex transfers to vendors. Supports both automatic (via counterparty_id) and manual matching. One transfer can only be matched to one vendor.';

