-- Migration: Create Brex API vendor tables and join tables
-- Creates api_brex_vendors, api_brex_vendors_clerk_users, and api_brex_vendors_clerk_orgs

-- Create api_brex_vendors table
CREATE TABLE IF NOT EXISTS "public"."api_brex_vendors" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "brex_vendor_id" text NOT NULL,
    "name" text,
    "email" text,
    "payment_instrument_id" text,
    "routing_number" text,
    "account_number" text,
    "account_type" text,
    "address_line1" text,
    "address_line2" text,
    "city" text,
    "state" text,
    "postal_code" text,
    "country" text,
    "phone" text,
    "vendor_type" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now(),
    "synced_at" timestamp with time zone,
    "raw_payload" jsonb,
    CONSTRAINT "api_brex_vendors_brex_vendor_id_key" UNIQUE ("brex_vendor_id"),
    CONSTRAINT "api_brex_vendors_pkey" PRIMARY KEY ("id")
);

-- Create api_brex_vendors_clerk_users join table
CREATE TABLE IF NOT EXISTS "public"."api_brex_vendors_clerk_users" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "brex_vendor_id" bigint NOT NULL,
    "clerk_user_id" bigint NOT NULL,
    "match_confidence" numeric(3,2),
    "match_method" text,
    "match_notes" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "api_brex_vendors_clerk_users_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "api_brex_vendors_clerk_users_brex_vendor_id_clerk_user_id_key" UNIQUE ("brex_vendor_id", "clerk_user_id"),
    CONSTRAINT "api_brex_vendors_clerk_users_brex_vendor_id_fkey" FOREIGN KEY ("brex_vendor_id") REFERENCES "public"."api_brex_vendors"("id") ON DELETE CASCADE,
    CONSTRAINT "api_brex_vendors_clerk_users_clerk_user_id_fkey" FOREIGN KEY ("clerk_user_id") REFERENCES "public"."auth_clerk_users"("id") ON DELETE CASCADE
);

-- Create api_brex_vendors_clerk_orgs join table
CREATE TABLE IF NOT EXISTS "public"."api_brex_vendors_clerk_orgs" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "brex_vendor_id" bigint NOT NULL,
    "clerk_org_id" bigint NOT NULL,
    "match_confidence" numeric(3,2),
    "match_method" text,
    "match_notes" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "api_brex_vendors_clerk_orgs_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "api_brex_vendors_clerk_orgs_brex_vendor_id_clerk_org_id_key" UNIQUE ("brex_vendor_id", "clerk_org_id"),
    CONSTRAINT "api_brex_vendors_clerk_orgs_brex_vendor_id_fkey" FOREIGN KEY ("brex_vendor_id") REFERENCES "public"."api_brex_vendors"("id") ON DELETE CASCADE,
    CONSTRAINT "api_brex_vendors_clerk_orgs_clerk_org_id_fkey" FOREIGN KEY ("clerk_org_id") REFERENCES "public"."auth_clerk_orgs"("id") ON DELETE CASCADE
);

-- Create indexes for api_brex_vendors
CREATE INDEX IF NOT EXISTS "api_brex_vendors_brex_vendor_id_idx" ON "public"."api_brex_vendors"("brex_vendor_id");
CREATE INDEX IF NOT EXISTS "api_brex_vendors_name_idx" ON "public"."api_brex_vendors"("name");
CREATE INDEX IF NOT EXISTS "api_brex_vendors_account_number_idx" ON "public"."api_brex_vendors"("account_number");

-- Create indexes for join tables
CREATE INDEX IF NOT EXISTS "api_brex_vendors_clerk_users_brex_vendor_id_idx" ON "public"."api_brex_vendors_clerk_users"("brex_vendor_id");
CREATE INDEX IF NOT EXISTS "api_brex_vendors_clerk_users_clerk_user_id_idx" ON "public"."api_brex_vendors_clerk_users"("clerk_user_id");
CREATE INDEX IF NOT EXISTS "api_brex_vendors_clerk_orgs_brex_vendor_id_idx" ON "public"."api_brex_vendors_clerk_orgs"("brex_vendor_id");
CREATE INDEX IF NOT EXISTS "api_brex_vendors_clerk_orgs_clerk_org_id_idx" ON "public"."api_brex_vendors_clerk_orgs"("clerk_org_id");

-- Enable RLS
ALTER TABLE "public"."api_brex_vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."api_brex_vendors_clerk_users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."api_brex_vendors_clerk_orgs" ENABLE ROW LEVEL SECURITY;

-- RLS Policies (basic - can be refined later)
-- Allow service_role full access
CREATE POLICY "Service role can manage api_brex_vendors" ON "public"."api_brex_vendors"
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role can manage api_brex_vendors_clerk_users" ON "public"."api_brex_vendors_clerk_users"
    FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Service role can manage api_brex_vendors_clerk_orgs" ON "public"."api_brex_vendors_clerk_orgs"
    FOR ALL USING (auth.role() = 'service_role');

-- Allow authenticated users to read their matched vendors
CREATE POLICY "Users can read their matched vendors" ON "public"."api_brex_vendors"
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM "public"."api_brex_vendors_clerk_users" avcu
            JOIN "public"."auth_clerk_users" acu ON avcu.clerk_user_id = acu.id
            WHERE avcu.brex_vendor_id = api_brex_vendors.id
            AND acu.clerk_user_id = auth.jwt()->>'sub'
        )
        OR EXISTS (
            SELECT 1 FROM "public"."api_brex_vendors_clerk_orgs" avco
            JOIN "public"."auth_clerk_orgs" aco ON avco.clerk_org_id = aco.id
            JOIN "public"."auth_clerk_orgs_members" acom ON acom.clerk_org_id = aco.id
            JOIN "public"."auth_clerk_users" acu ON acom.auth_clerk_users_id = acu.id
            WHERE avco.brex_vendor_id = api_brex_vendors.id
            AND acu.clerk_user_id = auth.jwt()->>'sub'
        )
    );

