-- Migration: Drop deprecated party FK columns from deal table and create deals_guarantors junction table
-- These columns are replaced by the deal_parties junction table

-- ============================================
-- STEP 1: Drop FK constraints first
-- ============================================

-- Contact FK constraints
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_broker_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_title_company_contact_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_insurance_carrier_contact_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_closing_agent_contact_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_appraisal_poc_contact_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_loan_buyer_contact_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_escrow_contact_id_fkey;

-- Auth clerk users FK constraints
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_account_executive_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_loan_processor_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_loan_opener_id_fkey;

-- Guarantor FK constraints
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_primary_guarantor_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_second_guarantor_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_third_guarantor_id_fkey;
ALTER TABLE deal DROP CONSTRAINT IF EXISTS deal_fourth_guarantor_id_fkey;

-- ============================================
-- STEP 2: Drop the columns (contact references)
-- ============================================

ALTER TABLE deal DROP COLUMN IF EXISTS broker_id;
ALTER TABLE deal DROP COLUMN IF EXISTS title_company_contact_id;
ALTER TABLE deal DROP COLUMN IF EXISTS insurance_carrier_contact_id;
ALTER TABLE deal DROP COLUMN IF EXISTS closing_agent_contact_id;
ALTER TABLE deal DROP COLUMN IF EXISTS appraisal_poc_contact_id;
ALTER TABLE deal DROP COLUMN IF EXISTS loan_buyer_contact_id;
ALTER TABLE deal DROP COLUMN IF EXISTS escrow_contact_id;

-- ============================================
-- STEP 3: Drop the columns (auth_clerk_users references)
-- ============================================

ALTER TABLE deal DROP COLUMN IF EXISTS account_executive_id;
ALTER TABLE deal DROP COLUMN IF EXISTS loan_processor_id;
ALTER TABLE deal DROP COLUMN IF EXISTS loan_opener_id;

-- ============================================
-- STEP 4: Drop the columns (guarantor references)
-- ============================================

ALTER TABLE deal DROP COLUMN IF EXISTS primary_guarantor_id;
ALTER TABLE deal DROP COLUMN IF EXISTS second_guarantor_id;
ALTER TABLE deal DROP COLUMN IF EXISTS third_guarantor_id;
ALTER TABLE deal DROP COLUMN IF EXISTS fourth_guarantor_id;

-- ============================================
-- STEP 5: Create deals_guarantors junction table
-- ============================================

CREATE TABLE public.deals_guarantors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_id bigint NOT NULL REFERENCES deal(id) ON DELETE CASCADE,
  guarantor_id bigint NOT NULL REFERENCES guarantor(id) ON DELETE CASCADE,
  is_primary boolean DEFAULT false,
  display_order int,
  notes text,
  created_at timestamptz DEFAULT now(),
  
  -- Prevent duplicate guarantor assignments to same deal
  CONSTRAINT deals_guarantors_unique UNIQUE (deal_id, guarantor_id)
);

COMMENT ON TABLE deals_guarantors IS 'Junction table linking deals to guarantors (many-to-many)';
COMMENT ON COLUMN deals_guarantors.deal_id IS 'The deal this guarantor is associated with';
COMMENT ON COLUMN deals_guarantors.guarantor_id IS 'Reference to guarantor table';
COMMENT ON COLUMN deals_guarantors.is_primary IS 'Whether this is the primary guarantor for the deal';
COMMENT ON COLUMN deals_guarantors.display_order IS 'Order of guarantors (1 = primary, 2 = secondary, etc.)';
COMMENT ON COLUMN deals_guarantors.notes IS 'Optional notes about this guarantor assignment';

-- ============================================
-- STEP 5a: Migrate data from temp table (if exists)
-- ============================================
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = '_temp_guarantor_migrations') THEN
    INSERT INTO deals_guarantors (deal_id, guarantor_id, is_primary, display_order, notes, created_at)
    SELECT deal_id, guarantor_id, is_primary, display_order, notes, created_at
    FROM _temp_guarantor_migrations
    ON CONFLICT (deal_id, guarantor_id) DO NOTHING;
    
    DROP TABLE _temp_guarantor_migrations;
    RAISE NOTICE 'Migrated guarantor data from temp table';
  END IF;
END $$;

-- Indexes
CREATE INDEX deals_guarantors_deal_id_idx ON deals_guarantors(deal_id);
CREATE INDEX deals_guarantors_guarantor_id_idx ON deals_guarantors(guarantor_id);

-- RLS
ALTER TABLE public.deals_guarantors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "deals_guarantors_select_authenticated" ON deals_guarantors 
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "deals_guarantors_insert_authenticated" ON deals_guarantors 
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "deals_guarantors_update_authenticated" ON deals_guarantors 
  FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "deals_guarantors_delete_authenticated" ON deals_guarantors 
  FOR DELETE TO authenticated USING (true);

-- ============================================
-- STEP 6: Drop deal_id from guarantor table (now redundant)
-- ============================================

-- First drop the FK constraint
ALTER TABLE guarantor DROP CONSTRAINT IF EXISTS guarantor_deal_id_fkey;
ALTER TABLE guarantor DROP CONSTRAINT IF EXISTS fk_deal;

-- Then drop the column
ALTER TABLE guarantor DROP COLUMN IF EXISTS deal_id;

