-- Migration: Create Brex API transfers table
-- Creates api_brex_transfers table with all transfer fields from Brex API

CREATE TABLE IF NOT EXISTS "public"."api_brex_transfers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "brex_transfer_id" text NOT NULL,
    "counterparty_id" text,
    "counterparty_type" text,
    "counterparty_payment_instrument_id" text,
    "counterparty_routing_number" text,
    "counterparty_account_number" text,
    "counterparty_name" text,
    "description" text,
    "payment_type" text,
    "amount" numeric(15,2),
    "amount_cents" bigint,
    "currency" text,
    "process_date" date,
    "originating_account_type" text,
    "originating_account_id" text,
    "originating_account_number" text,
    "originating_account_name" text,
    "status" text,
    "cancellation_reason" text,
    "estimated_delivery_date" date,
    "creator_user_id" text,
    "brex_created_at" timestamp with time zone,
    "display_name" text,
    "external_memo" text,
    "is_ppro_enabled" boolean,
    "fed_reference_number" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now(),
    "synced_at" timestamp with time zone,
    "sync_status" text DEFAULT 'pending',
    "sync_error_message" text,
    "raw_payload" jsonb,
    CONSTRAINT "api_brex_transfers_brex_transfer_id_key" UNIQUE ("brex_transfer_id"),
    CONSTRAINT "api_brex_transfers_pkey" PRIMARY KEY ("id")
);

-- Create foreign key to api_brex_vendors via counterparty_id
-- Note: This is a text reference, not a direct FK since counterparty_id is text
-- We'll handle the relationship in application logic

-- Create indexes
CREATE INDEX IF NOT EXISTS "api_brex_transfers_brex_transfer_id_idx" ON "public"."api_brex_transfers"("brex_transfer_id");
CREATE INDEX IF NOT EXISTS "api_brex_transfers_counterparty_id_idx" ON "public"."api_brex_transfers"("counterparty_id");
CREATE INDEX IF NOT EXISTS "api_brex_transfers_process_date_idx" ON "public"."api_brex_transfers"("process_date");
CREATE INDEX IF NOT EXISTS "api_brex_transfers_status_idx" ON "public"."api_brex_transfers"("status");
CREATE INDEX IF NOT EXISTS "api_brex_transfers_synced_at_idx" ON "public"."api_brex_transfers"("synced_at");

-- Enable RLS
ALTER TABLE "public"."api_brex_transfers" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Allow service_role full access
CREATE POLICY "Service role can manage api_brex_transfers" ON "public"."api_brex_transfers"
    FOR ALL USING (auth.role() = 'service_role');

-- Allow authenticated users to read transfers for their matched vendors
CREATE POLICY "Users can read transfers for their matched vendors" ON "public"."api_brex_transfers"
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM "public"."api_brex_vendors" av
            JOIN "public"."api_brex_vendors_clerk_users" avcu ON avcu.brex_vendor_id = av.id
            JOIN "public"."auth_clerk_users" acu ON avcu.clerk_user_id = acu.id
            WHERE av.brex_vendor_id = api_brex_transfers.counterparty_id
            AND acu.clerk_user_id = auth.jwt()->>'sub'
        )
        OR EXISTS (
            SELECT 1 FROM "public"."api_brex_vendors" av
            JOIN "public"."api_brex_vendors_clerk_orgs" avco ON avco.brex_vendor_id = av.id
            JOIN "public"."auth_clerk_orgs" aco ON avco.clerk_org_id = aco.id
            JOIN "public"."auth_clerk_orgs_members" acom ON acom.clerk_org_id = aco.id
            JOIN "public"."auth_clerk_users" acu ON acom.auth_clerk_users_id = acu.id
            WHERE av.brex_vendor_id = api_brex_transfers.counterparty_id
            AND acu.clerk_user_id = auth.jwt()->>'sub'
        )
    );

