-- Create lookup table for roles a contact can play ON A SPECIFIC DEAL
CREATE TABLE deal_role_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,      -- snake_case (stable, for code)
  name text NOT NULL,             -- Title Case (for display)
  description text,
  allows_multiple boolean DEFAULT true,  -- Can a deal have 2+ contacts in this role?
  display_order int,
  is_active boolean DEFAULT true,
  created_at timestamptz DEFAULT now()
);

-- Add table comment
COMMENT ON TABLE deal_role_types IS 'Lookup table defining roles that contacts can play on a specific deal (e.g., Title Agent, Broker, Guarantor)';
COMMENT ON COLUMN deal_role_types.code IS 'Snake_case identifier for programmatic use (stable, use in code/APIs)';
COMMENT ON COLUMN deal_role_types.name IS 'Human-readable display name';
COMMENT ON COLUMN deal_role_types.allows_multiple IS 'Whether a deal can have multiple contacts in this role';
COMMENT ON COLUMN deal_role_types.display_order IS 'Sort order for UI display';

-- Seed with deal-specific roles
INSERT INTO deal_role_types (code, name, allows_multiple, display_order) VALUES
  ('borrower', 'Borrower', true, 1),
  ('co_borrower', 'Co-Borrower', true, 2),
  ('guarantor', 'Guarantor', true, 3),
  ('broker', 'Broker', false, 10),
  ('loan_processor', 'Loan Processor', false, 11),
  ('account_executive', 'Account Executive', false, 12),
  ('title_agent', 'Title Agent', true, 20),
  ('escrow_agent', 'Escrow Agent', true, 21),
  ('settlement_agent', 'Settlement Agent', true, 22),
  ('closing_agent', 'Closing Agent', true, 23),
  ('insurance_agent', 'Insurance Agent', true, 30),
  ('appraiser', 'Appraiser', false, 40),
  ('appraisal_poc', 'Appraisal POC', false, 41),
  ('loan_buyer', 'Loan Buyer', false, 50),
  ('balance_sheet_investor', 'Balance Sheet Investor', true, 51),
  ('transaction_coordinator', 'Transaction Coordinator', true, 60),
  ('point_of_contact', 'Point of Contact', true, 70),
  ('referring_party', 'Referring Party', false, 80);

-- Enable RLS
ALTER TABLE deal_role_types ENABLE ROW LEVEL SECURITY;

-- Allow read access for all authenticated users (lookup table)
CREATE POLICY "Allow read access for authenticated users" 
  ON deal_role_types FOR SELECT 
  TO authenticated 
  USING (true);
