-- Create BSI join tables for distributions and statements to transactions
-- This migration syncs with PROD which has these tables

-- bsi_distributions_transactions: Many:1 relationship - multiple distributions roll up into one transaction
CREATE TABLE IF NOT EXISTS public.bsi_distributions_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  distribution_id bigint NOT NULL UNIQUE REFERENCES public.bsi_distributions(id) ON DELETE CASCADE,
  transaction_id bigint NOT NULL REFERENCES public.bsi_transactions(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now()
);

COMMENT ON TABLE public.bsi_distributions_transactions IS 'Junction table linking distributions to transactions. Many:1 relationship - multiple distributions from different deals roll up into one transaction (wire payment). Each distribution can only be linked to one transaction.';

-- Enable RLS
ALTER TABLE public.bsi_distributions_transactions ENABLE ROW LEVEL SECURITY;

-- bsi_statements_transactions: Many:Many relationship - statements can be paid by multiple transactions
CREATE TABLE IF NOT EXISTS public.bsi_statements_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  statement_id bigint NOT NULL REFERENCES public.bsi_statements(id) ON DELETE CASCADE,
  transaction_id bigint NOT NULL REFERENCES public.bsi_transactions(id) ON DELETE CASCADE,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(statement_id, transaction_id)
);

COMMENT ON TABLE public.bsi_statements_transactions IS 'Junction table linking statements to transactions. Supports Many:Many - one statement can be paid by multiple transactions, and one transaction can pay multiple statements (batch payments).';

-- Enable RLS
ALTER TABLE public.bsi_statements_transactions ENABLE ROW LEVEL SECURITY;

-- Grant permissions
GRANT ALL ON TABLE public.bsi_distributions_transactions TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.bsi_statements_transactions TO anon, authenticated, service_role;

