-- Create org_themes table (original name before rename)
-- This migration is idempotent - skips if auth_clerk_orgs_themes already exists

DO $$
BEGIN
  -- Only create if neither org_themes nor auth_clerk_orgs_themes exists
  IF NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'org_themes')
     AND NOT EXISTS (SELECT 1 FROM pg_tables WHERE schemaname = 'public' AND tablename = 'auth_clerk_orgs_themes') THEN
    
    CREATE TABLE public.org_themes (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      org_id bigint NOT NULL REFERENCES public.auth_clerk_orgs(id) ON DELETE CASCADE,
      name text NOT NULL,
      is_default boolean NOT NULL DEFAULT false,
      tokens_light jsonb NOT NULL DEFAULT '{}'::jsonb,
      tokens_dark jsonb NOT NULL DEFAULT '{}'::jsonb,
      radius jsonb NOT NULL DEFAULT '{"radius": "0.5rem"}'::jsonb,
      created_at timestamp with time zone NOT NULL DEFAULT now(),
      updated_at timestamp with time zone DEFAULT now(),
      created_by_user_id bigint REFERENCES public.auth_clerk_users(id)
    );

    COMMENT ON TABLE public.org_themes IS 'Organization theme customizations';
    COMMENT ON COLUMN public.org_themes.tokens_light IS 'JSONB object containing CSS variable values for light mode (e.g., {"background": "#ffffff", "foreground": "#0a0a0a"})';
    COMMENT ON COLUMN public.org_themes.tokens_dark IS 'JSONB object containing CSS variable values for dark mode';
    COMMENT ON COLUMN public.org_themes.radius IS 'JSONB object containing radius values (e.g., {"radius": "0.5rem"})';
    
    ALTER TABLE public.org_themes ENABLE ROW LEVEL SECURITY;
    
    RAISE NOTICE 'Created org_themes table';
  ELSE
    RAISE NOTICE 'Skipping org_themes creation - table already exists (as org_themes or auth_clerk_orgs_themes)';
  END IF;
END $$;

