-- Migration: Create junction table linking bsi_transactions to api_brex_transfers
-- Creates bsi_transactions_api_brex_transfers junction table

CREATE TABLE IF NOT EXISTS "public"."bsi_transactions_api_brex_transfers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "transaction_id" bigint NOT NULL,
    "brex_transfer_id" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT "bsi_transactions_api_brex_transfers_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "bsi_transactions_api_brex_transfers_transaction_id_brex_transfer_id_key" UNIQUE ("transaction_id", "brex_transfer_id"),
    CONSTRAINT "bsi_transactions_api_brex_transfers_transaction_id_fkey" FOREIGN KEY ("transaction_id") REFERENCES "public"."bsi_transactions"("id") ON DELETE CASCADE,
    CONSTRAINT "bsi_transactions_api_brex_transfers_brex_transfer_id_fkey" FOREIGN KEY ("brex_transfer_id") REFERENCES "public"."api_brex_transfers"("brex_transfer_id") ON DELETE CASCADE
);

-- Create indexes
CREATE INDEX IF NOT EXISTS "bsi_transactions_api_brex_transfers_transaction_id_idx" ON "public"."bsi_transactions_api_brex_transfers"("transaction_id");
CREATE INDEX IF NOT EXISTS "bsi_transactions_api_brex_transfers_brex_transfer_id_idx" ON "public"."bsi_transactions_api_brex_transfers"("brex_transfer_id");

-- Enable RLS
ALTER TABLE "public"."bsi_transactions_api_brex_transfers" ENABLE ROW LEVEL SECURITY;

-- RLS Policies
-- Allow service_role full access
CREATE POLICY "Service role can manage bsi_transactions_api_brex_transfers" ON "public"."bsi_transactions_api_brex_transfers"
    FOR ALL USING (auth.role() = 'service_role');

-- Allow authenticated users to read junction records for their transactions
CREATE POLICY "Users can read their transaction transfer links" ON "public"."bsi_transactions_api_brex_transfers"
    FOR SELECT USING (
        EXISTS (
            SELECT 1 FROM "public"."bsi_transactions" bt
            JOIN "public"."bsi_transactions_investors" bti ON bti.transaction_id = bt.id
            JOIN "public"."auth_clerk_users" acu ON bti.clerk_user_id = acu.id
            WHERE bt.id = bsi_transactions_api_brex_transfers.transaction_id
            AND acu.clerk_user_id = auth.jwt()->>'sub'
        )
        OR EXISTS (
            SELECT 1 FROM "public"."bsi_transactions" bt
            JOIN "public"."bsi_transactions_investors" bti ON bti.transaction_id = bt.id
            JOIN "public"."auth_clerk_orgs" aco ON bti.clerk_org_id = aco.id
            JOIN "public"."auth_clerk_orgs_members" acom ON acom.clerk_org_id = aco.id
            JOIN "public"."auth_clerk_users" acu ON acom.auth_clerk_users_id = acu.id
            WHERE bt.id = bsi_transactions_api_brex_transfers.transaction_id
            AND acu.clerk_user_id = auth.jwt()->>'sub'
        )
    );

