-- Migration: Create junction tables for document_files many-to-many relationships
-- Part of document system consolidation (Phase 1B)

---------------------------------------------------------------
-- Junction: document_files ↔ deals
---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_files_deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    deal_id BIGINT NOT NULL REFERENCES public.deal(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT, -- clerk_user_id
    UNIQUE(document_file_id, deal_id)
);

CREATE INDEX IF NOT EXISTS idx_document_files_deals_doc ON public.document_files_deals(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_deals_deal ON public.document_files_deals(deal_id);

---------------------------------------------------------------
-- Junction: document_files ↔ borrowers
---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_files_borrowers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    borrower_id BIGINT NOT NULL REFERENCES public.borrower(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT,
    UNIQUE(document_file_id, borrower_id)
);

CREATE INDEX IF NOT EXISTS idx_document_files_borrowers_doc ON public.document_files_borrowers(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_borrowers_borrower ON public.document_files_borrowers(borrower_id);

---------------------------------------------------------------
-- Junction: document_files ↔ properties
---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_files_properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    property_id BIGINT NOT NULL REFERENCES public.property(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT,
    UNIQUE(document_file_id, property_id)
);

CREATE INDEX IF NOT EXISTS idx_document_files_properties_doc ON public.document_files_properties(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_properties_property ON public.document_files_properties(property_id);

---------------------------------------------------------------
-- Junction: document_files ↔ guarantors
---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_files_guarantors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    guarantor_id BIGINT NOT NULL REFERENCES public.guarantor(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT,
    UNIQUE(document_file_id, guarantor_id)
);

CREATE INDEX IF NOT EXISTS idx_document_files_guarantors_doc ON public.document_files_guarantors(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_guarantors_guarantor ON public.document_files_guarantors(guarantor_id);

---------------------------------------------------------------
-- Junction: document_files ↔ companies (entities)
---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_files_companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES public.company(co_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT,
    UNIQUE(document_file_id, company_id)
);

CREATE INDEX IF NOT EXISTS idx_document_files_companies_doc ON public.document_files_companies(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_companies_company ON public.document_files_companies(company_id);

---------------------------------------------------------------
-- Junction: document_files ↔ auth_clerk_orgs (investor orgs)
---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_files_clerk_orgs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    clerk_org_id BIGINT NOT NULL REFERENCES public.auth_clerk_orgs(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT,
    UNIQUE(document_file_id, clerk_org_id)
);

CREATE INDEX IF NOT EXISTS idx_document_files_clerk_orgs_doc ON public.document_files_clerk_orgs(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_clerk_orgs_org ON public.document_files_clerk_orgs(clerk_org_id);

---------------------------------------------------------------
-- Junction: document_files ↔ auth_clerk_users (investor users)
---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_files_clerk_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    clerk_user_id BIGINT NOT NULL REFERENCES public.auth_clerk_users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT,
    UNIQUE(document_file_id, clerk_user_id)
);

CREATE INDEX IF NOT EXISTS idx_document_files_clerk_users_doc ON public.document_files_clerk_users(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_clerk_users_user ON public.document_files_clerk_users(clerk_user_id);
