-- Migration: Create document_tags and document_files_tags tables
-- 
-- This implements a proper tagging system with:
-- 1. Tag normalization via slug column
-- 2. Tag auto-complete via master tags list
-- 3. Tag metadata (created_by, created_at, updated_at)
-- 4. Tag management (rename/merge/delete tags globally)

-- Create document_tags table - master list of all tags
CREATE TABLE IF NOT EXISTS public.document_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,                                           -- Display name (e.g., "Statement")
    slug TEXT NOT NULL UNIQUE,                                    -- Normalized lowercase (e.g., "statement")
    description TEXT,                                             -- Optional tag description
    color TEXT,                                                   -- Optional hex color for UI
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by BIGINT REFERENCES public.auth_clerk_users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Create indexes for document_tags
CREATE INDEX IF NOT EXISTS idx_document_tags_slug ON public.document_tags(slug);
CREATE INDEX IF NOT EXISTS idx_document_tags_name ON public.document_tags(name);
CREATE INDEX IF NOT EXISTS idx_document_tags_created_by ON public.document_tags(created_by);

-- Add comments
COMMENT ON TABLE public.document_tags IS 'Master list of document tags with normalization and metadata';
COMMENT ON COLUMN public.document_tags.name IS 'Display name shown in UI';
COMMENT ON COLUMN public.document_tags.slug IS 'Normalized lowercase version for matching (prevents duplicates like Statement vs statement)';
COMMENT ON COLUMN public.document_tags.color IS 'Optional hex color code for tag badge display';

-- Create document_files_tags junction table
CREATE TABLE IF NOT EXISTS public.document_files_tags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_file_id BIGINT NOT NULL REFERENCES public.document_files(id) ON DELETE CASCADE,
    document_tag_id BIGINT NOT NULL REFERENCES public.document_tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by BIGINT REFERENCES public.auth_clerk_users(id) ON DELETE SET NULL,
    UNIQUE(document_file_id, document_tag_id)
);

-- Create indexes for document_files_tags
CREATE INDEX IF NOT EXISTS idx_document_files_tags_doc ON public.document_files_tags(document_file_id);
CREATE INDEX IF NOT EXISTS idx_document_files_tags_tag ON public.document_files_tags(document_tag_id);
CREATE INDEX IF NOT EXISTS idx_document_files_tags_created_by ON public.document_files_tags(created_by);

-- Add comments
COMMENT ON TABLE public.document_files_tags IS 'Junction table linking documents to tags (many-to-many)';

-- Create function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_document_tags_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for auto-updating updated_at
DROP TRIGGER IF EXISTS trigger_document_tags_updated_at ON public.document_tags;
CREATE TRIGGER trigger_document_tags_updated_at
    BEFORE UPDATE ON public.document_tags
    FOR EACH ROW
    EXECUTE FUNCTION public.update_document_tags_updated_at();

-- Create function to generate slug from name
CREATE OR REPLACE FUNCTION public.generate_tag_slug(tag_name TEXT)
RETURNS TEXT AS $$
BEGIN
    -- Convert to lowercase, replace spaces with hyphens, remove special chars
    RETURN lower(regexp_replace(regexp_replace(trim(tag_name), '\s+', '-', 'g'), '[^a-z0-9\-]', '', 'g'));
END;
$$ LANGUAGE plpgsql IMMUTABLE;

COMMENT ON FUNCTION public.generate_tag_slug IS 'Generates a URL-safe slug from a tag name for normalization';
