-- ============================================================================
-- Migration: Create Supporting Tables (Additive Strategy)
-- ============================================================================
-- Creates document_status, document_templates, document_template_variables,
-- document_types, email_templates, and dashboard_widgets tables.
--
-- Additive rules:
-- - UUID PK tables get BIGINT PK added, UUID kept as unique column
-- - organization_id UUID columns KEPT as-is, org_id BIGINT ADDED alongside
-- - No destructive changes to existing tables
-- ============================================================================

-- ============================================================================
-- PHASE 0: Create Trigger Functions (Prerequisites)
-- ============================================================================

CREATE OR REPLACE FUNCTION trigger_set_timestamp()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_current_timestamp_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- PHASE 1: document_statuses (renamed from document_status to avoid ENUM conflict)
-- NOTE: public.document_status already exists as an ENUM type in the database
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.document_statuses (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  organization_id uuid NULL,
  org_id bigint NULL,
  code text NOT NULL,
  label text NOT NULL,
  color text NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  is_terminal boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  is_default boolean NOT NULL DEFAULT false,
  CONSTRAINT document_statuses_pkey PRIMARY KEY (id),
  CONSTRAINT document_status_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES auth_clerk_orgs(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS document_statuses_code_global_uniq
  ON public.document_statuses (code) WHERE organization_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS document_statuses_code_org_uniq
  ON public.document_statuses (organization_id, code) WHERE organization_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS document_statuses_org_display_idx
  ON public.document_statuses (org_id, display_order, label);
CREATE UNIQUE INDEX IF NOT EXISTS idx_document_statuses_single_default
  ON public.document_statuses (is_default) WHERE is_default = true;

ALTER TABLE public.document_statuses ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PHASE 2: document_templates (UUID PK -> add BIGINT PK)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.document_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL,
  org_id bigint NULL,
  name text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz NULL,
  archived_by text NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  gjs_data jsonb NOT NULL,
  html_content text NOT NULL DEFAULT '',
  user_id text NOT NULL,
  CONSTRAINT document_templates_pkey PRIMARY KEY (id),
  CONSTRAINT document_templates_uuid_key UNIQUE (id_uuid),
  CONSTRAINT document_templates_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES auth_clerk_orgs(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS document_templates_org_updated_idx
  ON public.document_templates (org_id, updated_at DESC) WHERE org_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS document_templates_org_uuid_idx
  ON public.document_templates (organization_id);
CREATE INDEX IF NOT EXISTS idx_document_templates_not_archived
  ON public.document_templates (id) WHERE archived_at IS NULL;

CREATE TRIGGER set_document_templates_updated_at
  BEFORE UPDATE ON document_templates
  FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

ALTER TABLE public.document_templates ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PHASE 3: document_template_variables (UUID PK -> add BIGINT PK)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.document_template_variables (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  id_uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  name text NOT NULL,
  variable_type text NOT NULL,
  position integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  path text NULL,
  CONSTRAINT document_template_variables_pkey PRIMARY KEY (id),
  CONSTRAINT document_template_variables_uuid_key UNIQUE (id_uuid),
  CONSTRAINT document_template_variables_template_id_fkey FOREIGN KEY (template_id)
    REFERENCES document_templates(id_uuid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_dtv_position
  ON public.document_template_variables (template_id, position);

CREATE TRIGGER set_dtv_updated_at
  BEFORE UPDATE ON document_template_variables
  FOR EACH ROW EXECUTE FUNCTION trigger_set_timestamp();

ALTER TABLE public.document_template_variables ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PHASE 4: document_types (BIGINT PK, no change needed)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.document_types (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  document_category_id bigint NULL,
  document_name text NULL,
  document_description text NULL,
  display_order integer NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  archived_at timestamptz NULL,
  archived_by text NULL,
  ai_classification_prompt text NULL,
  label_format text NULL,
  label_format_resolved text NULL,
  CONSTRAINT document_types_pkey PRIMARY KEY (id),
  CONSTRAINT document_types_document_category_id_fkey FOREIGN KEY (document_category_id)
    REFERENCES document_categories(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_document_types_not_archived
  ON public.document_types (id) WHERE archived_at IS NULL;

ALTER TABLE public.document_types ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PHASE 5: email_templates (BIGINT PK, no change needed)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.email_templates (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  organization_id uuid NOT NULL,
  org_id bigint NULL,
  name text NOT NULL DEFAULT 'Untitled Template',
  subject text NOT NULL DEFAULT '',
  preview_text text NOT NULL DEFAULT '',
  from_address text NULL,
  reply_to text NULL,
  liveblocks_room_id text NULL,
  editor_json jsonb NOT NULL DEFAULT jsonb_build_object(
    'type', 'doc', 'content',
    jsonb_build_array(jsonb_build_object('type', 'paragraph'))
  ),
  email_output_html text NULL,
  email_output_text text NULL,
  styles jsonb NOT NULL DEFAULT '{}',
  status text NOT NULL DEFAULT 'draft',
  published_at timestamptz NULL,
  schema_version integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  blocknote_document jsonb NULL,
  uuid uuid NOT NULL DEFAULT gen_random_uuid(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_liveblocks_room_id_key UNIQUE (liveblocks_room_id),
  CONSTRAINT email_templates_uuid_key UNIQUE (uuid),
  CONSTRAINT email_templates_org_id_fkey FOREIGN KEY (org_id)
    REFERENCES auth_clerk_orgs(id) ON DELETE RESTRICT,
  CONSTRAINT email_templates_status_check CHECK (
    status = ANY (ARRAY['draft', 'published'])
  )
);

CREATE INDEX IF NOT EXISTS email_templates_org_id_idx
  ON public.email_templates (org_id) WHERE org_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS email_templates_org_uuid_idx
  ON public.email_templates (organization_id);
CREATE INDEX IF NOT EXISTS email_templates_status_idx
  ON public.email_templates (status);

CREATE TRIGGER email_templates_updated_at
  BEFORE UPDATE ON email_templates
  FOR EACH ROW EXECUTE FUNCTION set_current_timestamp_updated_at();

ALTER TABLE public.email_templates ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PHASE 6: dashboard_widgets (BIGINT PK, no change needed)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.dashboard_widgets (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  slot text NOT NULL,
  widget_type text NOT NULL,
  title text NOT NULL,
  subtitle text NULL,
  trend_label text NULL,
  trend_description text NULL,
  value_format text NULL,
  value_prefix text NULL,
  value_suffix text NULL,
  chart_type text NULL DEFAULT 'area',
  x_axis_key text NULL DEFAULT 'date',
  y_axis_key text NULL DEFAULT 'value',
  sql_query text NULL,
  created_at timestamptz NULL DEFAULT now(),
  updated_at timestamptz NULL DEFAULT now(),
  updated_by text NULL,
  icon text NULL,
  CONSTRAINT dashboard_widgets_pkey PRIMARY KEY (id),
  CONSTRAINT dashboard_widgets_slot_key UNIQUE (slot),
  CONSTRAINT dashboard_widgets_chart_type_check CHECK (
    chart_type = ANY (ARRAY['area', 'bar', 'line'])
  ),
  CONSTRAINT dashboard_widgets_slot_check CHECK (
    slot = ANY (ARRAY['kpi_1', 'kpi_2', 'kpi_3', 'kpi_4', 'chart_1'])
  ),
  CONSTRAINT dashboard_widgets_value_format_check CHECK (
    value_format = ANY (ARRAY['currency', 'number', 'percentage', 'integer'])
  ),
  CONSTRAINT dashboard_widgets_widget_type_check CHECK (
    widget_type = ANY (ARRAY['kpi', 'chart'])
  )
);

ALTER TABLE public.dashboard_widgets ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- PHASE 7: Seed document_status (5 global rows)
-- ============================================================================

INSERT INTO public.document_statuses (id, organization_id, org_id, code, label, color, display_order, is_active, is_terminal, created_at, is_default)
VALUES
  (1, NULL, NULL, 'draft', 'Draft', '#6B7280', 10, true, false, '2026-02-23 18:39:28.330503+00', false),
  (2, NULL, NULL, 'pending', 'Pending', '#F59E0B', 20, true, false, '2026-02-23 18:39:28.330503+00', true),
  (3, NULL, NULL, 'approved', 'Approved', '#10B981', 30, true, true, '2026-02-23 18:39:28.330503+00', false),
  (4, NULL, NULL, 'rejected', 'Rejected', '#EF4444', 40, true, true, '2026-02-23 18:39:28.330503+00', false),
  (5, NULL, NULL, 'archived', 'Archived', '#374151', 50, true, true, '2026-02-23 18:39:28.330503+00', false)
ON CONFLICT DO NOTHING;

-- ============================================================================
-- Verification (run manually)
-- ============================================================================
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_name IN ('document_status','document_templates','document_template_variables','document_types','email_templates','dashboard_widgets') ORDER BY table_name;
-- SELECT * FROM document_statuses;
