-- =============================================================================
-- Migration: Create Document Categories and Permissions System
-- =============================================================================
-- This migration creates:
-- 1. document_categories - Lookup table for document categories with metadata
-- 2. user_pref_document_categories_order - Per-user custom display order
-- 3. document_access_permissions - Permission matrix for deal roles → document categories
-- =============================================================================

-- =============================================================================
-- 1. DOCUMENT CATEGORIES LOOKUP TABLE
-- =============================================================================
CREATE TABLE public.document_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,              -- snake_case (matches existing enum values)
  name text NOT NULL,                     -- Title Case for display
  description text,                       -- Tooltip/help text
  storage_folder text NOT NULL,           -- Folder name in storage (may differ from code)
  icon text,                              -- Icon name for UI (e.g., 'file-text', 'home')
  default_display_order int,              -- System default sort order; users can override
  is_active boolean DEFAULT true,         -- Soft delete / deprecation flag
  is_internal_only boolean DEFAULT false, -- Only visible to internal admins
  created_at timestamptz DEFAULT now()
);

COMMENT ON TABLE document_categories IS 'Lookup table for document categories with metadata for UI and storage';
COMMENT ON COLUMN document_categories.code IS 'Snake_case identifier matching existing document_category enum values';
COMMENT ON COLUMN document_categories.storage_folder IS 'Folder name used in Supabase Storage paths';
COMMENT ON COLUMN document_categories.is_internal_only IS 'If true, only visible to internal admins (e.g., internal notes)';
COMMENT ON COLUMN document_categories.default_display_order IS 'System default sort order; users can override via user_pref_document_categories_order';

-- Seed with existing enum values + new categories
INSERT INTO document_categories (code, name, storage_folder, default_display_order, is_internal_only) VALUES
  -- Existing enum values
  ('application', 'Application', 'application', 1, false),
  ('appraisal', 'Appraisal', 'appraisal', 2, false),
  ('assets', 'Assets', 'assets', 3, false),
  ('closing', 'Closing', 'closing', 4, false),
  ('credit_and_background', 'Credit & Background', 'credit-and-background', 5, true),
  ('construction', 'Construction', 'construction', 6, false),
  ('environmental', 'Environmental', 'environmental', 7, false),
  ('experience', 'Experience', 'experience', 8, false),
  ('id', 'ID', 'id', 9, true),
  ('insurance', 'Insurance', 'insurance', 10, false),
  ('pricing', 'Pricing', 'pricing', 11, true),
  ('property', 'Property', 'property', 12, false),
  ('seasoning', 'Seasoning', 'seasoning', 13, false),
  ('servicing', 'Servicing', 'servicing', 14, false),
  ('title', 'Title', 'title', 15, false),
  ('entity', 'Entity', 'entity', 16, false),
  -- New categories for investor portal
  ('statements', 'Statements', 'statements', 20, false),
  ('payments', 'Payments', 'payments', 21, false),
  ('agreements', 'Agreements', 'agreements', 22, false),
  ('draw_requests', 'Draw Requests', 'draw-requests', 23, false),
  ('internal_notes', 'Internal Notes', 'internal-notes', 99, true);

-- RLS: Authenticated users can read active categories
ALTER TABLE document_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "document_categories_select_authenticated" ON document_categories
FOR SELECT TO authenticated
USING (is_active = true);

-- Admins can manage all categories
CREATE POLICY "document_categories_admin_all" ON document_categories
FOR ALL TO authenticated
USING (public.is_internal_admin())
WITH CHECK (public.is_internal_admin());

-- =============================================================================
-- 2. USER PREFERENCES: DOCUMENT CATEGORY ORDER
-- =============================================================================
CREATE TABLE public.user_pref_document_categories_order (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clerk_user_id text NOT NULL,            -- Clerk user ID string (e.g., "user_2x7...")
  document_categories_id bigint NOT NULL REFERENCES document_categories(id) ON DELETE CASCADE,
  display_order int NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  
  CONSTRAINT userpref_doc_category_order_unique UNIQUE (clerk_user_id, document_categories_id)
);

COMMENT ON TABLE user_pref_document_categories_order IS 'Per-user custom display order for document categories (drag-and-drop reordering)';
COMMENT ON COLUMN user_pref_document_categories_order.clerk_user_id IS 'Clerk user ID string (not FK - users may not exist in auth_clerk_users yet)';
COMMENT ON COLUMN user_pref_document_categories_order.display_order IS 'User-customized sort order (overrides document_categories.default_display_order)';

-- Index for fast lookup by user
CREATE INDEX idx_user_pref_doc_cat_order_clerk_user ON user_pref_document_categories_order(clerk_user_id);

-- RLS: Users can only see/modify their own preferences
ALTER TABLE user_pref_document_categories_order ENABLE ROW LEVEL SECURITY;

CREATE POLICY "user_pref_doc_cat_order_own" ON user_pref_document_categories_order
FOR ALL TO authenticated
USING (clerk_user_id = public.get_clerk_user_id())
WITH CHECK (clerk_user_id = public.get_clerk_user_id());

-- =============================================================================
-- 3. DOCUMENT ACCESS PERMISSIONS (Deal Role → Document Category Matrix)
-- =============================================================================
CREATE TABLE public.document_access_permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deal_role_types_id bigint NOT NULL REFERENCES deal_role_types(id) ON DELETE CASCADE,
  document_categories_id bigint NOT NULL REFERENCES document_categories(id) ON DELETE CASCADE,
  can_view boolean DEFAULT false,
  can_insert boolean DEFAULT false,       -- Can create new documents
  can_upload boolean DEFAULT false,       -- Can upload/replace files
  can_delete boolean DEFAULT false,
  created_at timestamptz DEFAULT now(),
  
  -- One permission row per role+category combo
  CONSTRAINT document_access_permissions_unique UNIQUE (deal_role_types_id, document_categories_id)
);

COMMENT ON TABLE document_access_permissions IS 'Permission matrix defining which deal roles can access which document categories';
COMMENT ON COLUMN document_access_permissions.can_view IS 'Can view/download documents in this category';
COMMENT ON COLUMN document_access_permissions.can_insert IS 'Can create new document records in this category';
COMMENT ON COLUMN document_access_permissions.can_upload IS 'Can upload/replace files for documents in this category';
COMMENT ON COLUMN document_access_permissions.can_delete IS 'Can delete documents in this category';

-- Indexes for common queries
CREATE INDEX idx_doc_access_perm_role ON document_access_permissions(deal_role_types_id);
CREATE INDEX idx_doc_access_perm_category ON document_access_permissions(document_categories_id);

-- RLS: Authenticated users can read permissions (needed for UI to show/hide actions)
ALTER TABLE document_access_permissions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "document_access_permissions_select_authenticated" ON document_access_permissions
FOR SELECT TO authenticated
USING (true);

-- Admins can manage permissions
CREATE POLICY "document_access_permissions_admin_all" ON document_access_permissions
FOR ALL TO authenticated
USING (public.is_internal_admin())
WITH CHECK (public.is_internal_admin());

-- =============================================================================
-- 4. SEED DEFAULT PERMISSIONS
-- =============================================================================
-- Balance Sheet Investor: View statements, payments, agreements
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view)
SELECT drt.id, dc.id, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'balance_sheet_investor'
  AND dc.code IN ('statements', 'payments', 'agreements');

-- Borrower: View and upload loan-related documents
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view, can_insert, can_upload)
SELECT drt.id, dc.id, true, true, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'borrower'
  AND dc.code IN ('application', 'assets', 'experience', 'entity', 'property');

-- Borrower: View-only for closing, insurance, title
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view)
SELECT drt.id, dc.id, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'borrower'
  AND dc.code IN ('closing', 'insurance', 'title');

-- Borrower: View and upload draw requests
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view, can_insert, can_upload)
SELECT drt.id, dc.id, true, true, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'borrower'
  AND dc.code = 'draw_requests';

-- Guarantor: View-only for application, closing, entity
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view)
SELECT drt.id, dc.id, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'guarantor'
  AND dc.code IN ('application', 'closing', 'entity');

-- Broker: View most documents
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view)
SELECT drt.id, dc.id, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'broker'
  AND dc.code IN ('application', 'appraisal', 'assets', 'closing', 'construction', 
                  'experience', 'insurance', 'property', 'title', 'entity', 'draw_requests');

-- Title Agent: View and upload title, closing documents
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view, can_insert, can_upload)
SELECT drt.id, dc.id, true, true, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'title_agent'
  AND dc.code IN ('title', 'closing');

-- Appraiser: View and upload appraisal documents
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view, can_insert, can_upload)
SELECT drt.id, dc.id, true, true, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'appraiser'
  AND dc.code = 'appraisal';

-- Insurance Agent: View and upload insurance documents
INSERT INTO document_access_permissions (deal_role_types_id, document_categories_id, can_view, can_insert, can_upload)
SELECT drt.id, dc.id, true, true, true
FROM deal_role_types drt, document_categories dc
WHERE drt.code = 'insurance_agent'
  AND dc.code = 'insurance';

-- =============================================================================
-- 5. HELPER FUNCTION: Check Deal Document Access
-- =============================================================================
CREATE OR REPLACE FUNCTION public.can_access_deal_document(
  p_deal_id bigint,
  p_document_category_code text,
  p_action text DEFAULT 'view'  -- 'view', 'insert', 'upload', 'delete'
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    -- Admins can do everything
    public.is_internal_admin()
    OR
    -- Check if user has a deal role that grants access
    EXISTS (
      SELECT 1
      FROM public.deal_roles dr
      JOIN public.auth_clerk_users acu ON dr.auth_clerk_users_id = acu.id
      JOIN public.document_access_permissions dap ON dr.deal_role_types_id = dap.deal_role_types_id
      JOIN public.document_categories dc ON dap.document_categories_id = dc.id
      WHERE dr.deal_id = p_deal_id
        AND acu.clerk_user_id = public.get_clerk_user_id()
        AND dc.code = p_document_category_code
        AND (
          (p_action = 'view' AND dap.can_view = true)
          OR (p_action = 'insert' AND dap.can_insert = true)
          OR (p_action = 'upload' AND dap.can_upload = true)
          OR (p_action = 'delete' AND dap.can_delete = true)
        )
    );
$$;

COMMENT ON FUNCTION public.can_access_deal_document IS 
  'Check if current user can perform an action on a document category for a specific deal';

GRANT EXECUTE ON FUNCTION public.can_access_deal_document TO authenticated;

-- =============================================================================
-- 6. VIEW: Get Categories with User Preferences
-- =============================================================================
CREATE OR REPLACE VIEW public.document_categories_with_order AS
SELECT 
  dc.id,
  dc.code,
  dc.name,
  dc.description,
  dc.storage_folder,
  dc.icon,
  dc.is_internal_only,
  COALESCE(udco.display_order, dc.default_display_order) AS display_order,
  CASE WHEN udco.id IS NOT NULL THEN true ELSE false END AS is_custom_order
FROM document_categories dc
LEFT JOIN user_pref_document_categories_order udco 
  ON dc.id = udco.document_categories_id 
  AND udco.clerk_user_id = public.get_clerk_user_id()
WHERE dc.is_active = true
ORDER BY COALESCE(udco.display_order, dc.default_display_order);

COMMENT ON VIEW public.document_categories_with_order IS 
  'Document categories with user-specific display order (falls back to system default)';

GRANT SELECT ON public.document_categories_with_order TO authenticated;
